export const ecuadorChartOfAccounts = [
  // --- ACTIVOS ---
  { code: '1', name: 'ACTIVOS', type: 'ASSET' },
  { code: '1.1', name: 'ACTIVOS CORRIENTES', type: 'ASSET' },
  { code: '1.1.1', name: 'Efectivo y Equivalentes al Efectivo', type: 'ASSET' },
  { code: '1.1.1.01', name: 'Caja General', type: 'ASSET' },
  { code: '1.1.1.02', name: 'Caja Chica', type: 'ASSET' },
  { code: '1.1.1.03', name: 'Bancos Locales', type: 'ASSET' },
  { code: '1.1.2', name: 'Activos Financieros', type: 'ASSET' },
  { code: '1.1.2.01', name: 'Inversiones a Corto Plazo', type: 'ASSET' },
  { code: '1.1.3', name: 'Cuentas y Documentos por Cobrar', type: 'ASSET' },
  { code: '1.1.3.01', name: 'Clientes Locales', type: 'ASSET' },
  { code: '1.1.3.02', name: 'Provisión Cuentas Incobrables', type: 'ASSET' },
  { code: '1.1.4', name: 'Activos por Impuestos Corrientes', type: 'ASSET' },
  { code: '1.1.4.01', name: 'Crédito Tributario a Favor de la Empresa (IVA)', type: 'ASSET' },
  { code: '1.1.4.02', name: 'Anticipo de Impuesto a la Renta', type: 'ASSET' },
  { code: '1.1.5', name: 'Inventarios', type: 'ASSET' },
  { code: '1.1.5.01', name: 'Inventario de Mercadería', type: 'ASSET' },
  { code: '1.2', name: 'ACTIVOS NO CORRIENTES', type: 'ASSET' },
  { code: '1.2.1', name: 'Propiedad, Planta y Equipo', type: 'ASSET' },
  { code: '1.2.1.01', name: 'Terrenos', type: 'ASSET' },
  { code: '1.2.1.02', name: 'Edificios', type: 'ASSET' },
  { code: '1.2.1.03', name: 'Muebles y Enseres', type: 'ASSET' },
  { code: '1.2.1.04', name: 'Equipo de Computación', type: 'ASSET' },
  { code: '1.2.1.05', name: 'Vehículos', type: 'ASSET' },
  { code: '1.2.2', name: 'Depreciación Acumulada', type: 'ASSET' },
  { code: '1.2.2.01', name: 'Depreciación Acumulada de Propiedad, Planta y Equipo', type: 'ASSET' },

  // --- PASIVOS ---
  { code: '2', name: 'PASIVOS', type: 'LIABILITY' },
  { code: '2.1', name: 'PASIVOS CORRIENTES', type: 'LIABILITY' },
  { code: '2.1.1', name: 'Cuentas y Documentos por Pagar', type: 'LIABILITY' },
  { code: '2.1.1.01', name: 'Proveedores Locales', type: 'LIABILITY' },
  { code: '2.1.2', name: 'Obligaciones con Instituciones Financieras', type: 'LIABILITY' },
  { code: '2.1.2.01', name: 'Préstamos Bancarios por Pagar Corto Plazo', type: 'LIABILITY' },
  { code: '2.1.3', name: 'Obligaciones con la Administración Tributaria', type: 'LIABILITY' },
  { code: '2.1.3.01', name: 'IVA por Pagar', type: 'LIABILITY' },
  { code: '2.1.3.02', name: 'Retenciones en la Fuente por Pagar', type: 'LIABILITY' },
  { code: '2.1.4', name: 'Obligaciones con el IESS', type: 'LIABILITY' },
  { code: '2.1.4.01', name: 'Aportes al IESS por Pagar', type: 'LIABILITY' },
  { code: '2.1.5', name: 'Obligaciones con Empleados', type: 'LIABILITY' },
  { code: '2.1.5.01', name: 'Sueldos por Pagar', type: 'LIABILITY' },
  { code: '2.1.5.02', name: 'Beneficios Sociales por Pagar (13ro, 14to, Vacaciones)', type: 'LIABILITY' },
  { code: '2.2', name: 'PASIVOS NO CORRIENTES', type: 'LIABILITY' },
  { code: '2.2.1', name: 'Obligaciones Financieras a Largo Plazo', type: 'LIABILITY' },

  // --- PATRIMONIO ---
  { code: '3', name: 'PATRIMONIO', type: 'EQUITY' },
  { code: '3.1', name: 'Capital Social', type: 'EQUITY' },
  { code: '3.2', name: 'Reservas', type: 'EQUITY' },
  { code: '3.2.1', name: 'Reserva Legal', type: 'EQUITY' },
  { code: '3.3', name: 'Resultados Acumulados', type: 'EQUITY' },
  { code: '3.3.1', name: 'Utilidades Acumuladas de Ejercicios Anteriores', type: 'EQUITY' },
  { code: '3.4', name: 'Resultados del Ejercicio', type: 'EQUITY' },
  { code: '3.4.1', name: 'Utilidad o Pérdida del Ejercicio', type: 'EQUITY' },

  // --- INGRESOS ---
  { code: '4', name: 'INGRESOS', type: 'REVENUE' },
  { code: '4.1', name: 'Ingresos Ordinarios', type: 'REVENUE' },
  { code: '4.1.1', name: 'Ventas de Bienes', type: 'REVENUE' },
  { code: '4.1.2', name: 'Prestación de Servicios', type: 'REVENUE' },
  { code: '4.1.3', name: 'Devoluciones y Descuentos en Ventas', type: 'REVENUE' },
  { code: '4.2', name: 'Otros Ingresos', type: 'REVENUE' },

  // --- GASTOS ---
  { code: '5', name: 'GASTOS', type: 'EXPENSE' },
  { code: '5.1', name: 'Gastos de Operación', type: 'EXPENSE' },
  { code: '5.1.1', name: 'Gastos de Administración', type: 'EXPENSE' },
  { code: '5.1.1.01', name: 'Sueldos y Salarios', type: 'EXPENSE' },
  { code: '5.1.1.02', name: 'Aportes al Seguro Social', type: 'EXPENSE' },
  { code: '5.1.1.03', name: 'Beneficios Sociales', type: 'EXPENSE' },
  { code: '5.1.1.04', name: 'Arriendos', type: 'EXPENSE' },
  { code: '5.1.1.05', name: 'Servicios Básicos (Agua, Luz, Teléfono)', type: 'EXPENSE' },
  { code: '5.1.1.06', name: 'Honorarios Profesionales', type: 'EXPENSE' },
  { code: '5.1.1.07', name: 'Depreciaciones', type: 'EXPENSE' },
  { code: '5.1.2', name: 'Gastos de Ventas', type: 'EXPENSE' },
  { code: '5.1.2.01', name: 'Publicidad y Propaganda', type: 'EXPENSE' },
  { code: '5.2', name: 'Gastos Financieros', type: 'EXPENSE' },
  { code: '5.2.1', name: 'Intereses Bancarios', type: 'EXPENSE' },
];
